name: manual workflow

on:
  workflow_dispatch:
    

jobs:
  first-workflow:
    runs-on: windows-latest

    steps:
    - name: First steps
      run: |
        echo "Hello world"
        echo "Hello world"