name: cron workflow

on:
  schedule:
    - cron: '*/5 * * * *'
    

jobs:
  first-workflow:
    runs-on: windows-latest

    steps:
    - name: specific time trigger
      run: |
        echo "Hello world"
        echo "Hello world"